# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DateAppDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DateAppDemo
pod 'Alamofire', '~> 5.2'
pod 'lottie-ios'  

target 'DateAppDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DateAppDemoUITests' do
    # Pods for testing
  end

end
